import { GoogleGenAI } from "@google/genai";
import type { Rarity } from "@/types/game";

type SelectedOption = {
  stepKey: string;
  stepTitle: string;
  name: string;
  rarity: Rarity;
  image: string;
};

type RequestBody = {
  playerName: string;
  characterTitle: string;
  finalRarity: Rarity;
  selectedOptions: SelectedOption[];
};

export async function POST(request: Request) {
  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return Response.json(
        { error: "Missing GEMINI_API_KEY" },
        { status: 500 }
      );
    }

    const body = (await request.json()) as RequestBody;

    const ai = new GoogleGenAI({
      apiKey,
    });

    const choices = body.selectedOptions
      .map(
        (option) =>
          `- ${option.stepTitle}: ${option.name} (${option.rarity})`
      )
      .join("\n");

    const prompt = `
You are writing the final destiny text for an anime character generator called Anime Forge.

Write one dramatic, polished, anime-style result text.

Rules:
- Write in English.
- Length: 130 to 180 words.
- Tone: epic, mysterious, emotional, serious.
- Do not sound childish.
- Do not use bullet points.
- Do not mention that this was generated by AI.
- Mention the character's strength level through the final rarity.
- The stronger the rarity, the more world-changing the fate should feel.
- Common should still feel meaningful, but grounded.
- Rare should feel like hidden potential.
- Epic should feel powerful and dangerous.
- Legendary should feel mythic and world-shaping.
- Use the character choices naturally.
- Do not repeat every choice as a list.
- End with a strong final sentence.

Character:
Name: ${body.playerName}
Title: ${body.characterTitle}
Final Rarity: ${body.finalRarity}

Choices:
${choices}
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const destinyText = response.text?.trim();

    if (!destinyText) {
      return Response.json(
        { error: "No destiny text generated" },
        { status: 500 }
      );
    }

    return Response.json({
      destinyText,
    });
  } catch (error) {
    console.error(error);

    return Response.json(
      { error: "Failed to generate destiny text" },
      { status: 500 }
    );
  }
}